var json = {
  games: {
    "1v1.LOL": { path: "1v1-lol", aliases: [], categories: ["online", "battle"] },
    "10 Minutes Till Dawn": { path: "10-minutes-till-dawn", aliases: [], categories: [] },
    "2048": { path: "2048", aliases: [], categories: [] },
    "Basket Random": { path: "basket-random", aliases: [], categories: [] },
    "Basketball Stars": { path: "basketball-stars", aliases: [], categories: [] },
    "Bitcoin Clicker": { path: "bitcoin-clicker", aliases: [], categories: [] },
    "Bit Life": { path: "bit-life", aliases: [], categories: [] },
    "Boxing Random": { path: "boxing-random", aliases: [], categories: [] },
    "Capybara Clicker": { path: "capybara-clicker", aliases: [], categories: [] },
    "Chrome Dino": { path: "chrome-dino", aliases: [], categories: [] },
    "Cookie Clicker": { path: "cookie-clicker", aliases: [], categories: [] },
    "Crossy Road": { path: "crossy-road", aliases: [], categories: [] },
    "Doge Miner": { path: "doge-miner", aliases: [], categories: [] },
    "Drift Boss": { path: "drift-boss", aliases: [], categories: [] },
    "Drive Mad": { path: "drive-mad", aliases: [], categories: [] },
    "Escape Road": { path: "escape-road", aliases: [], categories: [] },
    "Fireboy and Watergirl": { path: "fireboy-and-watergirl", aliases: [], categories: [] },
    "Flappy Bird": { path: "flappy-bird", aliases: [], categories: [] },
    "Fortnite Temu Version": { path: "Fortnite", aliases: [], categories: [] },
    "Geometry Dash Lite": { path: "geometry-dash-lite", aliases: [], categories: [] },
    "Geometry Dash Remastered": { path: "geometry-dash-remastered", aliases: [], categories: [] },
    "Gun Spin": { path: "gunspin", aliases: [], categories: [] },
    "Happy Wheels": { path: "flash/?game=happywheels", aliases: [], categories: [] },
    "Infinite Wordle": { path: "infinite-wordle", aliases: [], categories: [] },
    "Idle Breakout": { path: "idle-breakout", aliases: [], categories: [] },
    "Monkey Mart": { path: "monkey-mart", aliases: [], categories: [] },
    "MotoX3M": { path: "motox3m", aliases: [], categories: [] },
    "OvO": { path: "ovo/1.4.4", aliases: [], categories: [] },
    "People Playground": { path: "people-playground", aliases: [], categories: [] },
    "Pokemon Emerald": { path: "Pokemon-Emerald", aliases: [], categories: [] },
    "Retro Bowl": { path: "retro-bowl", aliases: [], categories: [] },
    "Run 3": { path: "run-3", aliases: [], categories: [] },
    "SkinWalker": { path: "skinwalker", aliases: [], categories: [] },
    "Slice Master": { path: "slice-master", aliases: [], categories: [] },
    "Slope": { path: "slope", aliases: [], categories: [] },
    "Smash Karts": { path: "smash-karts", aliases: [], categories: [] },
    "Snow Rider": { path: "snowrider", aliases: [], categories: [] },
    "Soccer Random": { path: "soccer-random", aliases: [], categories: [] },
    "Stickman Hook": { path: "stickman-hook", aliases: [], categories: [] },
    "Subway Surfers": { path: "subway-surfers", aliases: [], categories: [] },
    "Temple Run 2": { path: "temple-run-2", aliases: [], categories: [] },
    "Tiny Fishing": { path: "tiny-fishing", aliases: [], categories: [] },
    "Tunnel Rush": { path: "tunnel-rush", aliases: [], categories: [] },
    "Vex 3": { path: "vex-3", aliases: [], categories: [] },
    "Vex 4": { path: "vex-4", aliases: [], categories: [] },
    "Vex 5": { path: "vex-5", aliases: [], categories: [] },
    "Vex 6": { path: "vex-6", aliases: [], categories: [] },
    "Vex 7": { path: "vex-7", aliases: [], categories: [] },
    "Volley Random": { path: "volley-random", aliases: [], categories: [] },
    "Web OSU": { path: "web-osu", aliases: [], categories: [] },
    "X Trench Run": { path: "x-trench-run", aliases: [], categories: [] },
    "Yohoho": { path: "yohoho", aliases: [], categories: [] }
  },
  themes: {},
  config: {
    proxy: false,
    proxyPath: ""
  }
};
